{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    {{- include "kube-resource-report.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ include "kube-resource-report.fullname" . }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-resource-report.fullname" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "kube-resource-report.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
